// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::{Insertable, Queryable};
use serde::{Deserialize, Serialize};

use crate::schema::users;

#[derive(Queryable, Debug)]
pub struct Credential {
    pub id: i32,
    pub password: String,
}

#[derive(Queryable, Debug)]
pub struct Permission {
    pub id: i32,
    pub title: String,
}

#[derive(Queryable, Debug)]
pub struct RolePermission {
    pub id: i32,
    pub role_id: Option<i32>,
    pub permission_id: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Role {
    pub id: i32,
    pub title: String,
}

#[derive(Insertable, Deserialize, Queryable, Debug, Serialize)]
#[serde(crate = "rocket::serde")]
#[diesel(table_name = users)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub lastname: String,
    pub email: String,
    pub created_at: String,
    pub role_id: i32,
    pub credential_id: i32,
}

#[derive(Deserialize)]
pub struct NewUser {
    pub name: String,
    pub lastname: String,
    pub email: String,
    pub role_id: i32,
}
